### PR TITLE
Compile and generate python package for PsrPopPy

### PR DESCRIPTION
**Pull request by mattpitkin**
In case it is useful to anyone else I've tried creating a build system that compiles the Fortran libraries and makes PsrPopPy into a python package. I've done this using [enscons](https://bitbucket.org/dholth/enscons) (a new build and packaging system based on [scons](http://www.scons.org/).

To do this I've had to rearrange the repository a bit, but I've tried to make sure all previous links and executables still work. In the base directory running
```
sudo python setup.py install
```
should compile the library, install the python package (in the relevant python location in `/usr/local/lib` by default), and copy the `dosurvey`, `populate` and `evolve` executables into `/usr/loca/bin`. It will also create a python wheel, and if running with `python setup.py sdist` a source distribution too. This could potentially be added to [PyPI](https://pypi.python.org/pypi) if deemed valuable.

Anyway, if you think these patches could be useful, whilst hopefully not causing any issues for other users, or have any questions, please let me know.

### CODE REVIEW

**Comment by samb8s** [comment]
Hi Matt - thanks!
I won't be able to take a look at this until the weekend, probably (not being an astronomer anymore!) but this sounds really awesome. Thank you for your work!

**Comment by mattpitkin** [comment]
Great, thanks. There's no rush.

**Comment by demorest** [comment]
Hi guys,  this sounds useful.  Any chance of getting it merged in?  

Matt, I'm not familiar with enscons and couldn't figure out how to set the install prefix to something besides /usr/local.  The standard `python setup.py install --prefix=/my/install/dir` type thing didn't seem to work, and there isn't an obvious option for this in the setup.py usage info.  Any tips?  Thanks.

**Comment by mattpitkin** [comment]
Hi Paul, I'll need to look into a bit more detail into how to set the install path from the command line. I think it can be done through the SConstruct file like I've done [here](https://github.com/mattpitkin/DNest4/blob/master/SConstruct). At the moment it's (I think) just the psrpoppy binaries that are forced to be installed in `/usr/local/bin`, whilst the rest of the library goes in the default python install location, so it might change if you install in a virtual environment (although I've not tested that). I'll have a play around tomorrow and see what I can do, but your more than welcome to experiment yourself.

**Comment by demorest** [comment]
OK, thanks Matt.  Editing the `installprefix` variable in the SConstruct file got the executables installed in the right place, but the python stuff was still being sent to /usr/local (via pip).  Running pip from the command line with an added `--prefix` option worked around this for now though.

**Comment by mattpitkin** [comment]
@demorest - I've pushed a change to the `SConstruct` file so you can hopefully now just run:

```bash
python setup.py install --prefix=$MY_PREFERED_INSTALL_LOCATION
```

Alternatively, I've also added the option that you can use a pip-like `--user` flag to install as a user to `~/.local`, e.g.

```bash
python setup.py install --user
```

Let me know if this works.

**Comment by samb8s** [comment]
Sorry for all delays. Busy moving house and being on vacation this week when activity picked up!

**Pull request merged**
